### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#125]
# SPRINT PLANING: SPRINT 4

>start: 26.10.2017
end: 13.11.2017

## SPRINT GOAL
> As a user, I want to transform CSARs into target artifacts for kubernetes, Amazon Web Services and CloudFoundry.
> These CSARs are supposed to only contain supported NodeTypes (at least one NodeType will be supported)
> As a developer, I want to have a unified architecture for all plugins.
> As a plugin developer, I want to access a simplified interface when interacting with the TOSCA template

## GENERAL
- build CSAR that only contains supported NodeTypes
  - for testing purposes
  - for demo purposes

## PLUGINS
Assigned:
- Amazon Cloud Formation: @mklopp
- Kubernetes: @nfode, @mmunozba
- CloudFoundry: @jmuell
Joins later: @oferch
- [ ] Design a common plugin architecture
- [ ] Agree on Target Artifact conventions, e.g. file naming (see #148)
- [x] Create NodeType support document, which shows current NodeType support status of the plugins
- [x] Prioritize NodeTypes (which establishes the implementation order)
- [x] Agree on the first NodeTypes which shall get implemented
- [ ] Implement first NodeType

## CORE 
Assigned: @hnicke, @c-mueller
- [x] Refactor
- [x] Logging Persistency
- ~~Property persistency~~  < `next sprint`
- [x] Fix read transformations from disk
- [x] Redesign PluginFileAccess
- [ ] TServiceTemplate processor
   ~~-  Merge Templates~~ < `next sprint`
    - [ ] Inject Types
    - [ ] Build Graph (with JGraphT)
    - [ ] Write interface for plugins to offer graph
        - this has high priority

## API 
Assigned: @c-mueller
- [x] Rework properties
- [x] Generate API documentation
- [x] Exchange custom status API with Spring Actuator

## CLI
Assigned: @oferch
- [x] Unified look on different operating systems
- [x] Implement proper debugging
- [x] Implement properties 
- [x] Rework Help/Usage texts
