### ISSUE TITLE
Converter: Markdown -> Latex -> PDF

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#2]
To have a visual appealing documentation we need to convert it from md to latex and then to pdf.
For this task I recommend **Sphinx**. 
As an example I used the eclipse/winery dev docu. 

**TODO**
- [ ] fix the broken links
- [x] convert all the files to .rst before building the doc 
- [ ] optimize code listings

**Comment by nfode** [comment]
The example can be found [here](https://github.com/nfode/TOSCAna/tree/doc/docs).

**Comment by hnicke** [comment]
Actually, you've provided a mechanism for converting our .md to pdf, the issue title claims the oposite.
What is the current status of the issue?
Are here any open tasks?

**Comment by nfode** [comment]
Opened the task at night so the title contains a mistake and check the todos.
