### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#204]
# SPRINT PLANING: SPRINT 5

>start: 13.11.2017
end: 27.11.2017

## SPRINT GOAL
?

## GENERAL
- [ ] build CSAR that only contains supported NodeTypes
  - for testing purposes
  - for demo purposes

## PLUGINS
Assigned:
- Amazon Cloud Formation: @mklopp
- Kubernetes: @nfode, @mmunozba, @c-mueller 
- CloudFoundry: @jmuell
Joins later: @oferch
- [ ] general plugin architecture
- [ ] Design a common plugin architecture
- [x] Agree on Target Artifact conventions, e.g. file naming (see #148)
- [ ] Create NodeType support document, which shows current NodeType support status of the plugins
- [ ] Implement first NodeType

## SERVER
- [x] design and implement transformation lifecycle
- [x] rework PluginFileAccess #191 

## MODEL 
Assigned: @hnicke
- [x] implement the whole model #173
- [x] model and implement non-normative types
- [ ] Design and Implement interface for plugins to offer graph

## CLI
Assigned: @oferch
- [ ] refactor (duplicated code)
- [ ] integrate retrofit wrapper
- [ ] add correct exit codes
- [ ] fix `toscana status`
