### ISSUE TITLE
Implement the web app features

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#419]
**TODO:**
- [ ] implement the main view
- [ ] implement the csar upload
- [ ] implement the new transformation creation
- [ ] implement the csar overview page
- [ ] implement the transformation overview page
- [ ] implement the status bar

**TODO *[NOT IMPORTANT]*:**
- [ ] replace the "angular-file-picker-fixed"-package with the original "angular-file-picker" package if there is a never version available
- [ ] style all the buttons 
  - [ ] the back button in the transformation creation modal
  - [ ] the csar item toogle button (it should fill the whole height)
